##### Configuration file for VSpecialItems. #####

### eng(English) or ger(German) ###
Language: eng

### You can add biomes simply by adding them to the list. ###
### Don't forget to set a custom name for the biome in the languages file! ###
changeBiomeItem:
  item: Stick
  biomes:
    - PLAINS
    - FOREST
    - DESERT
    - BEACH
    - SWAMP
    - JUNGLE
    - RIVER
    - SAVANNA
    - BADLANDS
    - OCEAN
    - MOUNTAINS
    - TAIGA
    - SNOWY_TUNDRA
    - SNOWY_TAIGA
    - ICE_SPIKES
    - SNOWY_TAIGA_MOUNTAINS
    - SUNFLOWER_PLAINS
    - FLOWER_FOREST
    - FROZEN_RIVER
    - WARM_OCEAN
    - LUKEWARM_OCEAN
    - DEEP_LUKEWARM_OCEAN
    - DEEP_OCEAN
    - COLD_OCEAN
    - DEEP_COLD_OCEAN
    - FROZEN_OCEAN
    - DEEP_FROZEN_OCEAN
    - TAIGA_MOUNTAINS
    - BIRCH_FOREST
    - DARK_FOREST
    - BAMBOO_JUNGLE
    - DRIPSTONE_CAVES
    - LUSH_CAVES
    - MEADOW
    - GROVE
    - SNOWY_SLOPES
    - FROZEN_PEAKS
    - JAGGED_PEAKS
    - STONY_PEAKS
