name: VSpecialItems
main: com.github.Viduality.VSpecialItems.VSpecialItems
version: '${minecraft.plugin.version}'
author: Viduality
api-version: '1.15'


commands:
  VSpecialItems:
    description: Opens a menu with all current special items
    usage: /vspecialitems
    permission: SpecialItems.Command
    permission-message: You don't have permission!

permissions:
  VSpecialItems.Command:
    description: Gives access to the special items command.
    default: op
  VSpecialItems.ChangeBiomeItemUse:
    description: Allows to use the special item "ChangeBiome".
    default: op